- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
    cache_valid_time: 3600  # <-- Supprimez cette ligne
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

